### ISSUE TITLE
LeXun.Microsoft.Owin.Security.Alipay 

### ISSUE THREAD

**Issue by vicenteyu** [ArcherTrister/LeXun.Security.OAuth#4]
LeXun.Microsoft.Owin.Security.Alipay 的依赖项有问题。

**Comment by vicenteyu** [comment]
“Alipay.AopSdk (>= 3.2.4)”

**Comment by ArcherTrister** [comment]
请在项目下手动添加 【LeXun.Alipay.AopSdk】 nuget包试试

**Comment by ArcherTrister** [comment]
请在项目下手动添加 【LeXun.Alipay.AopSdk】 nuget包试试

**Comment by ArcherTrister** [comment]
@vicenteyu 请在该项目下添加 【LeXun.Alipay.AopSdk】 nuget包试试，NF版的已经好久不用了，具体原因我也排查一下

**Comment by ArcherTrister** [comment]
@vicenteyu  已改并且发布了1.0.1版本,感谢！
